### ISSUE TITLE
Why Community Matters?

### ISSUE THREAD

**Issue by ApsRajput** [laravellivedelhi/talks#12]
# Title
Why Community Matters?
---

## Brief description about the content to be covered
Benefits of being in the community for career growth, seamless learning and self development.
--

## Prerequisites & reading material (Distributed before the session) 
--

## Time required for the talk
30 min
--

## Link to slides / demos
--

## About yourself (Please include social media links, twitter, facebook)
Co founder at Webshot Technologies (webshot.in)
LinkedIn : https://www.linkedin.com/in/aps-rajput/
Twitter : https://twitter.com/coderrajput
--

## Your open source contributions (if any)
--

## Availability (When would you be able to give the talk?) 
--

##Any comments
--

**Comment by saurav-webkul** [comment]
Hi @ApsRajput 

Please make sure that no machine software is installed on your system.

**Comment by ApsRajput** [comment]
> Hi @ApsRajput
> 
> Please make sure that no machine software is installed on your system.

Sure, I have it installed
