### ISSUE TITLE
Performance in Laravel 🚀

### ISSUE THREAD

**Issue by naviace** [laravellivedelhi/talks#7]
# Title
Performance in Laravel 🚀

## Brief description about the content to be covered
Some practical tips to improve and monitor the performance of any laravel application

## Prerequisites & reading material (Distributed before the session) 
--

## Time required for the talk
~20 minutes

## Link to slides / demos
WIP

## About yourself (Please include social media links, twitter, facebook)
[Linkedin](https://www.linkedin.com/in/naviworks/)

## Availability (When would you be able to give the talk?) 
September 3, 2022

**Comment by saurav-webkul** [comment]
Hi,

Thank you for submitting the talk. Would you be available for 15th October session?

**Comment by naviace** [comment]
Hi @saurav-webkul, yes I'd be happy to deliver the talk on 15th October.

**Comment by saurav-webkul** [comment]
Thanks for the acknowledgement.

**Comment by saurav-webkul** [comment]
Hi,

Please make sure nomachine software is installed on your system when you come here on 15th to deliver the talk: https://www.nomachine.com/

Also, provide us with a passport size photograph of yours and your social handles

**Comment by saurav-webkul** [comment]
Hi,

Is there any way to connect with you for tomorrow's talk?
