### ISSUE TITLE
Code Smartly: Tips, Tricks & Good Practices in Laravel

### ISSUE THREAD

**Issue by pathak-vikash** [laravellivedelhi/talks#8]
# Title
---
Code Smartly: Tips, Tricks & Good Practices in Laravel

## Brief description about the content to be covered

Everyone could code and achieve the functinality in their efficient way but it's always have a concern the code you have written is in effective way.

In this talk consits tips, tricks and good practices in Laravel that can descrease your coding hours in effective ways.

## Prerequisites & reading material (Distributed before the session) 

  -  PHP Programming Skills
  -  Basic Laravel Concepts
  
## Time required for the talk

 - 30 Mins

## About yourself (Please include social media links, twitter, facebook)

Having good experience in different technologies like PHP, Javascript, Golang, .Net and it's framworks. I've started working with Laravel since it was in earlier stage 4.2. And continously working with Microservices application with Lumen.

  - LinkedIn: https://www.linkedin.com/in/vikashpathak
  - Twitter: https://twitter.com/mr_vikashpathak
  - Facebook: https://www.facebook.com/vikashpathak91
  
## Availability (When would you be able to give the talk?) 

 - OCT 15th, 2022

**Comment by saurav-webkul** [comment]
Pic: https://drive.google.com/file/d/1bhbroDIQBEmBHkeub3189U4mxH6jwkTe/view
