### ISSUE TITLE
How to build FOSS CRM software using Laravel and its importance for a business

### ISSUE THREAD

**Issue by surajkumardagur** [laravellivedelhi/talks#9]
# Title

How to build FOSS CRM software using Laravel and its importance fora  business

---

## Brief description of the content to be covered

In this talk, I will cover how an organization can build FOSS CRM software using Laravel and what kind of benefits they will get with it. 

--

## Prerequisites & reading material (Distributed before the session) 

Beginner-level understanding of CRM

--

## Time required for the talk

30 Min
--

## About yourself (Please include social media links, Twitter, Facebook)

A  professional with more than 5 years of experience in the IT industry. Working with the team of Krayin the FOSS CRM from ground zero. 

Linkedin - https://www.linkedin.com/in/surajkumardagur/
Twitter - https://twitter.com/surajkumardagur
Facebook - https://www.facebook.com/surajkumardagur

--

## Your open source contributions (if any)
--

## Availability (When would you be able to give the talk?) 

October 15th, 2022

--

**Comment by saurav-webkul** [comment]
![img_0368](https://user-images.githubusercontent.com/32482149/194750134-7c8bf938-0611-4b43-9a31-67e98f0e9541.jpg)
